#!/bin/bash

################################################################################
# Quick CUDA Symlink Fix Script
#
# This script fixes the current CUDA symlink issue by running the environment
# setup logic from install_cuda_alongside.sh on the already-installed CUDA 12.6.
#
# Usage:
#   sudo ./fix_current_cuda_symlinks.sh
#
# Author: Claude Code
# Date: 2025-12-16
################################################################################

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

log() { echo -e "${GREEN}[INFO]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; }
success() { echo -e "${BLUE}[SUCCESS]${NC} $1"; }
step() { echo -e "${CYAN}[STEP]${NC} $1"; }

# Check root
if [[ $EUID -ne 0 ]]; then
    error "This script must be run as root (sudo)"
    exit 1
fi

CUDA_INSTALL_DIR="/usr/local/cuda-12.6"
CUDA_MAJOR_MINOR="12.6"

echo ""
echo "════════════════════════════════════════════════════════════════"
echo "  CUDA 12.6 Symlink Fix"
echo "════════════════════════════════════════════════════════════════"
echo ""

# Verify CUDA 12.6 is installed
if [[ ! -d "$CUDA_INSTALL_DIR" ]]; then
    error "CUDA 12.6 not found at $CUDA_INSTALL_DIR"
    exit 1
fi

if [[ ! -f "$CUDA_INSTALL_DIR/bin/nvcc" ]]; then
    error "nvcc not found in $CUDA_INSTALL_DIR/bin/"
    exit 1
fi

log "Found CUDA 12.6 at $CUDA_INSTALL_DIR"

# -------------------------------------------------------------------------
# Configure update-alternatives for CUDA version management
# -------------------------------------------------------------------------
step "Configuring update-alternatives for CUDA 12.6..."

priority=126

# Check if this version is already registered
if update-alternatives --query cuda 2>/dev/null | grep -q "$CUDA_INSTALL_DIR"; then
    log "CUDA 12.6 already registered with update-alternatives, updating..."
    update-alternatives --remove cuda "$CUDA_INSTALL_DIR" 2>/dev/null || true
fi

# Register CUDA 12.6
log "Registering CUDA 12.6 with update-alternatives (priority: $priority)"
update-alternatives --install /usr/local/cuda cuda "$CUDA_INSTALL_DIR" "$priority"

# Set as default
log "Setting CUDA 12.6 as default"
update-alternatives --set cuda "$CUDA_INSTALL_DIR"

success "/usr/local/cuda symlink configured via update-alternatives"

# Verify the symlink
actual_target=$(readlink -f /usr/local/cuda)
log "Verified: /usr/local/cuda -> $actual_target"

# -------------------------------------------------------------------------
# Configure ldconfig for library resolution
# -------------------------------------------------------------------------
step "Configuring ldconfig for CUDA 12.6..."

ldconfig_file="/etc/ld.so.conf.d/cuda-12.6.conf"

cat > "$ldconfig_file" << EOF
# CUDA 12.6 library paths
# Auto-generated by fix_current_cuda_symlinks.sh
$CUDA_INSTALL_DIR/lib64
$CUDA_INSTALL_DIR/lib
$CUDA_INSTALL_DIR/targets/x86_64-linux/lib
EOF

success "Created: $ldconfig_file"

# Update ldconfig cache
log "Updating library cache..."
ldconfig

success "Library cache updated"

# Verify library resolution
echo ""
step "Verifying library resolution..."
echo ""
log "Checking libcudart.so resolution:"
ldconfig -p | grep libcudart | head -5

echo ""
step "Current update-alternatives configuration..."
echo ""
update-alternatives --display cuda

echo ""
echo "════════════════════════════════════════════════════════════════"
success "CUDA 12.6 symlinks and library paths fixed!"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "Configuration Summary:"
echo "  • /usr/local/cuda now points to: $CUDA_INSTALL_DIR"
echo "  • Libraries are registered with ldconfig"
echo "  • update-alternatives is configured"
echo ""
echo "Next Steps:"
echo "  1. Open a new terminal or run: source /etc/profile.d/cuda-gorgonia.sh"
echo "  2. Verify with: nvcc --version"
echo "  3. Test your Go CUDA build"
echo ""
echo "To switch between CUDA versions in the future:"
echo "  sudo update-alternatives --config cuda"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
